In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";")
df

,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
0,BMW,520,40000.0,2017.0,190,Gebraucht,Diesel,"4,5",46900
1,Volvo,XC60,42656.0,2017.0,190,Gebraucht,Diesel,"4,7",32930
2,Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,"5,8",40930
3,Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,"5,2",30990
4,Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,"5,9",3200
5,Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,"7,6",39930
6,Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,"7,2",17000
7,Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,"4,7",10240
8,Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,"5,7",3550
9,Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5,3200
10,Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,"5,5",24990
11,Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5,14990
12,Kia,Rio,4.0,NaN,84,Neu,Benzin,"5,5",14250
13,Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790
14,BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,"4,5",21950
15,Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,"6,9",2890
16,Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,"5,1",9450
17,Mazda,6,NaN,NaN,194,Neu,Benzin,"6,8",34190
18,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,"6,3",23190
19,Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,"7,6",60990

In [7]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",")
df

,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
0,BMW,520,40000.0,2017.0,190,Gebraucht,Diesel,4.5,46900
1,Volvo,XC60,42656.0,2017.0,190,Gebraucht,Diesel,4.7,32930
2,Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,5.8,40930
3,Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,5.2,30990
4,Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,5.9,3200
5,Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,7.6,39930
6,Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,7.2,17000
7,Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,4.7,10240
8,Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,5.7,3550
9,Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5.0,3200
10,Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,5.5,24990
11,Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5.0,14990
12,Kia,Rio,4.0,NaN,84,Neu,Benzin,5.5,14250
13,Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790
14,BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,4.5,21950
15,Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,6.9,2890
16,Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,5.1,9450
17,Mazda,6,NaN,NaN,194,Neu,Benzin,6.8,34190
18,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,6.3,23190
19,Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,7.6,60990

In [8]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",", names=["hersteller",
                        "modell",
                        "km_stand",
                        "baujahr",
                        "ps",
                        "zustand",
                        "kraftstoff",
                        "verbrauch",
                        "preis"])
df

,hersteller,modell,km_stand,baujahr,ps,zustand,kraftstoff,verbrauch,preis
0,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
1,BMW,520,40000,2017,190,Gebraucht,Diesel,"4,5",46900
2,Volvo,XC60,42656,2017,190,Gebraucht,Diesel,"4,7",32930
3,Volvo,XC90,111183,2015,224,Gebraucht,Diesel,"5,8",40930
4,Audi,Q3,42922,2016,184,Gebraucht,Diesel,"5,2",30990
5,Seat,Ibiza,138000,2008,69,Gebraucht,Benzin,"5,9",3200
6,Volkswagen,Tiguan,13189,2018,179,Gebraucht,Benzin,"7,6",39930
7,Volkswagen,Touran,45000,2014,140,Gebraucht,Benzin,"7,2",17000
8,Volkswagen,Passat,100,2018,67,Gebraucht,Benzin,"4,7",10240
9,Audi,A3,345000,2006,170,Gebraucht,Diesel,"5,7",3550
10,Volvo,V50,260000,2008,109,Gebraucht,Diesel,5,3200
11,Renault,Scenic,2000,2018,140,Neu,Benzin,"5,5",24990
12,Renault,Clio,2000,2018,90,Neu,Benzin,5,14990
13,Kia,Rio,4,NaN,84,Neu,Benzin,"5,5",14250
14,Peugeot,307,52750,2004,109,Gebraucht,Benzin,NaN,2790
15,BMW,218,42346,2015,150,Gebraucht,Diesel,"4,5",21950
16,Volkswagen,Caddy,156600,2007,105,Gebraucht,Diesel,"6,9",2890
17,Fiat,500,6917,2013,69,Gebraucht,Benzin,"5,1",9450
18,Mazda,6,NaN,NaN,194,Neu,Benzin,"6,8",34190
19,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,"6,3",23190
20,Volkswagen,T6,26537,2017,204,Jahreswagen,Diesel,"7,6",60990

In [9]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",header=None, names=["hersteller",
                        "modell",
                        "km_stand",
                        "baujahr",
                        "ps",
                        "zustand",
                        "kraftstoff",
                        "verbrauch",
                        "preis"])
df

,hersteller,modell,km_stand,baujahr,ps,zustand,kraftstoff,verbrauch,preis
0,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
1,BMW,520,40000,2017,190,Gebraucht,Diesel,"4,5",46900
2,Volvo,XC60,42656,2017,190,Gebraucht,Diesel,"4,7",32930
3,Volvo,XC90,111183,2015,224,Gebraucht,Diesel,"5,8",40930
4,Audi,Q3,42922,2016,184,Gebraucht,Diesel,"5,2",30990
5,Seat,Ibiza,138000,2008,69,Gebraucht,Benzin,"5,9",3200
6,Volkswagen,Tiguan,13189,2018,179,Gebraucht,Benzin,"7,6",39930
7,Volkswagen,Touran,45000,2014,140,Gebraucht,Benzin,"7,2",17000
8,Volkswagen,Passat,100,2018,67,Gebraucht,Benzin,"4,7",10240
9,Audi,A3,345000,2006,170,Gebraucht,Diesel,"5,7",3550
10,Volvo,V50,260000,2008,109,Gebraucht,Diesel,5,3200
11,Renault,Scenic,2000,2018,140,Neu,Benzin,"5,5",24990
12,Renault,Clio,2000,2018,90,Neu,Benzin,5,14990
13,Kia,Rio,4,NaN,84,Neu,Benzin,"5,5",14250
14,Peugeot,307,52750,2004,109,Gebraucht,Benzin,NaN,2790
15,BMW,218,42346,2015,150,Gebraucht,Diesel,"4,5",21950
16,Volkswagen,Caddy,156600,2007,105,Gebraucht,Diesel,"6,9",2890
17,Fiat,500,6917,2013,69,Gebraucht,Benzin,"5,1",9450
18,Mazda,6,NaN,NaN,194,Neu,Benzin,"6,8",34190
19,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,"6,3",23190
20,Volkswagen,T6,26537,2017,204,Jahreswagen,Diesel,"7,6",60990

In [10]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",header=0, names=["hersteller",
                        "modell",
                        "km_stand",
                        "baujahr",
                        "ps",
                        "zustand",
                        "kraftstoff",
                        "verbrauch",
                        "preis"])
df

,hersteller,modell,km_stand,baujahr,ps,zustand,kraftstoff,verbrauch,preis
0,BMW,520,40000.0,2017.0,190,Gebraucht,Diesel,4.5,46900
1,Volvo,XC60,42656.0,2017.0,190,Gebraucht,Diesel,4.7,32930
2,Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,5.8,40930
3,Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,5.2,30990
4,Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,5.9,3200
5,Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,7.6,39930
6,Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,7.2,17000
7,Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,4.7,10240
8,Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,5.7,3550
9,Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5.0,3200
10,Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,5.5,24990
11,Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5.0,14990
12,Kia,Rio,4.0,NaN,84,Neu,Benzin,5.5,14250
13,Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790
14,BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,4.5,21950
15,Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,6.9,2890
16,Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,5.1,9450
17,Mazda,6,NaN,NaN,194,Neu,Benzin,6.8,34190
18,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,6.3,23190
19,Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,7.6,60990

In [17]:
df_subset = df[["hersteller", "modell", "preis"]]
df_subset

    hersteller  modell  preis
0          BMW     520  46900
1        Volvo    XC60  32930
2        Volvo    XC90  40930
3         Audi      Q3  30990
4         Seat   Ibiza   3200
5   Volkswagen  Tiguan  39930
6   Volkswagen  Touran  17000
7   Volkswagen  Passat  10240
8         Audi      A3   3550
9        Volvo     V50   3200
10     Renault  Scenic  24990
11     Renault    Clio  14990
12         Kia     Rio  14250
13     Peugeot     307   2790
14         BMW     218  21950
15  Volkswagen   Caddy   2890
16        Fiat     500   9450
17       Mazda       6  34190
18       Mazda    MX-5  23190
19  Volkswagen      T6  60990

In [18]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv",
    sep=";",
    decimal=",",
    usecols=["Hersteller", "Modell", "Preis"]
)
df

    Hersteller  Modell  Preis
0          BMW     520  46900
1        Volvo    XC60  32930
2        Volvo    XC90  40930
3         Audi      Q3  30990
4         Seat   Ibiza   3200
5   Volkswagen  Tiguan  39930
6   Volkswagen  Touran  17000
7   Volkswagen  Passat  10240
8         Audi      A3   3550
9        Volvo     V50   3200
10     Renault  Scenic  24990
11     Renault    Clio  14990
12         Kia     Rio  14250
13     Peugeot     307   2790
14         BMW     218  21950
15  Volkswagen   Caddy   2890
16        Fiat     500   9450
17       Mazda       6  34190
18       Mazda    MX-5  23190
19  Volkswagen      T6  60990

In [24]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",skiprows=3, names=["hersteller",
                        "modell",
                        "km_stand",
                        "baujahr",
                        "ps",
                        "zustand",
                        "kraftstoff",
                        "verbrauch",
                        "preis"])
df

,hersteller,modell,km_stand,baujahr,ps,zustand,kraftstoff,verbrauch,preis
0,Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,5.8,40930
1,Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,5.2,30990
2,Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,5.9,3200
3,Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,7.6,39930
4,Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,7.2,17000
5,Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,4.7,10240
6,Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,5.7,3550
7,Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5.0,3200
8,Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,5.5,24990
9,Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5.0,14990
10,Kia,Rio,4.0,NaN,84,Neu,Benzin,5.5,14250
11,Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790
12,BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,4.5,21950
13,Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,6.9,2890
14,Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,5.1,9450
15,Mazda,6,NaN,NaN,194,Neu,Benzin,6.8,34190
16,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,6.3,23190
17,Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,7.6,60990

In [27]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",skipfooter=3)
df

C:\Users\kedir\AppData\Local\Temp\ipykernel_19504\3241119771.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",skipfooter=3)

,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
0,BMW,520,40000,2017.0,190,Gebraucht,Diesel,4.5,46900
1,Volvo,XC60,42656,2017.0,190,Gebraucht,Diesel,4.7,32930
2,Volvo,XC90,111183,2015.0,224,Gebraucht,Diesel,5.8,40930
3,Audi,Q3,42922,2016.0,184,Gebraucht,Diesel,5.2,30990
4,Seat,Ibiza,138000,2008.0,69,Gebraucht,Benzin,5.9,3200
5,Volkswagen,Tiguan,13189,2018.0,179,Gebraucht,Benzin,7.6,39930
6,Volkswagen,Touran,45000,2014.0,140,Gebraucht,Benzin,7.2,17000
7,Volkswagen,Passat,100,2018.0,67,Gebraucht,Benzin,4.7,10240
8,Audi,A3,345000,2006.0,170,Gebraucht,Diesel,5.7,3550
9,Volvo,V50,260000,2008.0,109,Gebraucht,Diesel,5.0,3200
10,Renault,Scenic,2000,2018.0,140,Neu,Benzin,5.5,24990
11,Renault,Clio,2000,2018.0,90,Neu,Benzin,5.0,14990
12,Kia,Rio,4,NaN,84,Neu,Benzin,5.5,14250
13,Peugeot,307,52750,2004.0,109,Gebraucht,Benzin,NaN,2790
14,BMW,218,42346,2015.0,150,Gebraucht,Diesel,4.5,21950
15,Volkswagen,Caddy,156600,2007.0,105,Gebraucht,Diesel,6.9,2890
16,Fiat,500,6917,2013.0,69,Gebraucht,Benzin,5.1,9450

In [28]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",",nrows=10, names=["hersteller",
                        "modell",
                        "km_stand",
                        "baujahr",
                        "ps",
                        "zustand",
                        "kraftstoff",
                        "verbrauch",
                        "preis"])
df

,hersteller,modell,km_stand,baujahr,ps,zustand,kraftstoff,verbrauch,preis
0,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
1,BMW,520,40000,2017,190,Gebraucht,Diesel,"4,5",46900
2,Volvo,XC60,42656,2017,190,Gebraucht,Diesel,"4,7",32930
3,Volvo,XC90,111183,2015,224,Gebraucht,Diesel,"5,8",40930
4,Audi,Q3,42922,2016,184,Gebraucht,Diesel,"5,2",30990
5,Seat,Ibiza,138000,2008,69,Gebraucht,Benzin,"5,9",3200
6,Volkswagen,Tiguan,13189,2018,179,Gebraucht,Benzin,"7,6",39930
7,Volkswagen,Touran,45000,2014,140,Gebraucht,Benzin,"7,2",17000
8,Volkswagen,Passat,100,2018,67,Gebraucht,Benzin,"4,7",10240
9,Audi,A3,345000,2006,170,Gebraucht,Diesel,"5,7",3550

In [30]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",", index_col="Hersteller")
df

,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis
Hersteller,,,,,,,,
BMW,520,40000.0,2017.0,190,Gebraucht,Diesel,4.5,46900
Volvo,XC60,42656.0,2017.0,190,Gebraucht,Diesel,4.7,32930
Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,5.8,40930
Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,5.2,30990
Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,5.9,3200
Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,7.6,39930
Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,7.2,17000
Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,4.7,10240
Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,5.7,3550
Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5.0,3200
Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,5.5,24990
Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5.0,14990
Kia,Rio,4.0,NaN,84,Neu,Benzin,5.5,14250
Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790
BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,4.5,21950
Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,6.9,2890
Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,5.1,9450
Mazda,6,NaN,NaN,194,Neu,Benzin,6.8,34190
Mazda,MX-5,NaN,NaN,132,Neu,Benzin,6.3,23190
Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,7.6,60990

In [31]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",", index_col=["Hersteller","Modell"])
df

                   Kilometerstand  Baujahr   PS      Zustand Kraftstoff  \
Hersteller Modell
BMW        520            40000.0   2017.0  190    Gebraucht     Diesel
Volvo      XC60           42656.0   2017.0  190    Gebraucht     Diesel
           XC90          111183.0   2015.0  224    Gebraucht     Diesel
Audi       Q3             42922.0   2016.0  184    Gebraucht     Diesel
Seat       Ibiza         138000.0   2008.0   69    Gebraucht     Benzin
Volkswagen Tiguan         13189.0   2018.0  179    Gebraucht     Benzin
           Touran         45000.0   2014.0  140    Gebraucht     Benzin
           Passat           100.0   2018.0   67    Gebraucht     Benzin
Audi       A3            345000.0   2006.0  170    Gebraucht     Diesel
Volvo      V50           260000.0   2008.0  109    Gebraucht     Diesel
Renault    Scenic          2000.0   2018.0  140          Neu     Benzin
           Clio            2000.0   2018.0   90          Neu     Benzin
Kia        Rio                4.0      NaN   84          Neu     Benzin
Peugeot    307            52750.0   2004.0  109    Gebraucht     Benzin
BMW        218            42346.0   2015.0  150    Gebraucht     Diesel
Volkswagen Caddy         156600.0   2007.0  105    Gebraucht     Diesel
Fiat       500             6917.0   2013.0   69    Gebraucht     Benzin
Mazda      6                  NaN      NaN  194          Neu     Benzin
           MX-5               NaN      NaN  132          Neu     Benzin
Volkswagen T6             26537.0   2017.0  204  Jahreswagen     Diesel

                   Verbrauch  Preis
Hersteller Modell
BMW        520           4.5  46900
Volvo      XC60          4.7  32930
           XC90          5.8  40930
Audi       Q3            5.2  30990
Seat       Ibiza         5.9   3200
Volkswagen Tiguan        7.6  39930
           Touran        7.2  17000
           Passat        4.7  10240
Audi       A3            5.7   3550
Volvo      V50           5.0   3200
Renault    Scenic        5.5  24990
           Clio          5.0  14990
Kia        Rio           5.5  14250
Peugeot    307           NaN   2790
BMW        218           4.5  21950
Volkswagen Caddy         6.9   2890
Fiat       500           5.1   9450
Mazda      6             6.8  34190
           MX-5          6.3  23190
Volkswagen T6            7.6  60990

In [35]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",", true_values=["Ja"], false_values=["Nein"])
df

,Hersteller,Modell,Kilometerstand,Baujahr,PS,Zustand,Kraftstoff,Verbrauch,Preis,Gebraucht
0,BMW,520,40000.0,2017.0,190,Gebraucht,Diesel,4.5,46900,True
1,Volvo,XC60,42656.0,2017.0,190,Gebraucht,Diesel,4.7,32930,True
2,Volvo,XC90,111183.0,2015.0,224,Gebraucht,Diesel,5.8,40930,True
3,Audi,Q3,42922.0,2016.0,184,Gebraucht,Diesel,5.2,30990,True
4,Seat,Ibiza,138000.0,2008.0,69,Gebraucht,Benzin,5.9,3200,True
5,Volkswagen,Tiguan,13189.0,2018.0,179,Gebraucht,Benzin,7.6,39930,True
6,Volkswagen,Touran,45000.0,2014.0,140,Gebraucht,Benzin,7.2,17000,True
7,Volkswagen,Passat,100.0,2018.0,67,Gebraucht,Benzin,4.7,10240,True
8,Audi,A3,345000.0,2006.0,170,Gebraucht,Diesel,5.7,3550,True
9,Volvo,V50,260000.0,2008.0,109,Gebraucht,Diesel,5.0,3200,True
10,Renault,Scenic,2000.0,2018.0,140,Neu,Benzin,5.5,24990,False
11,Renault,Clio,2000.0,2018.0,90,Neu,Benzin,5.0,14990,False
12,Kia,Rio,4.0,NaN,84,Neu,Benzin,5.5,14250,False
13,Peugeot,307,52750.0,2004.0,109,Gebraucht,Benzin,NaN,2790,True
14,BMW,218,42346.0,2015.0,150,Gebraucht,Diesel,4.5,21950,True
15,Volkswagen,Caddy,156600.0,2007.0,105,Gebraucht,Diesel,6.9,2890,True
16,Fiat,500,6917.0,2013.0,69,Gebraucht,Benzin,5.1,9450,True
17,Mazda,6,NaN,NaN,194,Neu,Benzin,6.8,34190,False
18,Mazda,MX-5,NaN,NaN,132,Neu,Benzin,6.3,23190,False
19,Volkswagen,T6,26537.0,2017.0,204,Jahreswagen,Diesel,7.6,60990,False

In [ ]:
df = pd.read_csv(r"C:\Users\kedir\Documents\IT\python_excercises\Auto.csv", sep=";", decimal=",", true_values=["Ja"], false_values=["Nein"])
df