In [26]:
import pandas as pd

daten = {
    "KundenID": list(range(1, 22)),
    "Vorname": ["Luke", "Leia", "Frodo", "Aragorn", "Hermione", "Darth", "Indiana", "Lara", "Neo", "Trinity",
                "Gandalf", "Bilbo", "Jack", "Tony", "Bruce", "Clark", "Diana", "Peter", "Frodo", "Aragorn", "Sherlock"],
    "Nachname": ["Skywalker", "Organa.", "Baggins", "N/a", "Granger", "Vader", "Jones", "Croft", "Anderson", "Moss",
                "Greyhame...", "NaN", ".Sparrow", " Stark", "/Wayne", "Kent/", "Prince", "Parker", "...Baggins", "Elessar", "Holmes"],
    "Telefonnummer": [
        "0176-9876543", "(030) 2345678", "040 876 5432", "0151|567-8901", "+49 (0)170 123 45 67",
        "0049 160 987 6543", "0221/3456789", "0711 2345-67", "06131/87 65 43", "+49 152-765 4321",
        "089 34-56789", "01522/987 6543", "NaN", "N/a", "123-456-7890", "844|5435|333", "4353/45 345",
        "+49 170 9998887", "(040) 567 7890", "030 5678 123", "+49 176-543 2109"
    ],
    "Adresse": [
        "/Hauptstraße 12, Berlin, 10115...", "N/a", "Mittelstraße 34, München, 80331--", "--Ringstraße 78, Hamburg, 20095--",
        "N/a", "/Königsallee 22, Düsseldorf, 40210", "...Marktplatz 5, Stuttgart, 70173", "N/a", "N/a", "N/a",
        "Lindenstraße 9, Frankfurt, 60313", "--Goethestraße 14, Leipzig, 04109--", "...Bergstraße 67, Bremen, 28195",
        "/Schillerstraße 3, Dresden, 01067", "N/a", "Mozartstraße 2, Köln, 50667...", "Wilhelmstraße 6, Hannover, 30159",
        "--Friedrichstraße 10, Potsdam, 14467", "Humboldtstraße 8, Erfurt, 99084--", "Brandenburger Tor 1, Berlin, 10117",
        "/Kurfürstendamm 21, Berlin, 10719/"
    ],
    "Zahlender Kunde": ["Ja", "J", "Nein", "N", "N/a", "Ja", "Nein", "N", "Ja", "J", "N", "Ja", "Nein", "Ja", "J", "N", "N/a", "Ja", "J", "N", "Nein"],
    "Nicht kontaktieren": ["Nein", "N", "Ja", "J", "N/a", "Nein", "Ja", "J", "Nein", "N", "J", "Ja", "Nein", "Nein", "J", "J", "N/a", "Nein", "J", "Nein", "Ja"],
    "Unnötige Spalte": ["Löschen"] * 21
}

#DataFrame erstellen
df = pd.DataFrame(daten)

#Duplikate für KundenID 19 und 20 hinzufügen
df.loc[19] = df.loc[18]  # Duplikat der Zeile 18 für Zeile 19
df.loc[20] = df.loc[18]  # Duplikat der Zeile 18 für Zeile 20
df

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,0176-9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa.,(030) 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,040 876 5432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,N/a,0151|567-8901,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 (0)170 123 45 67,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,0049 160 987 6543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,0221/3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,0711 2345-67,N/a,N,J,Löschen
8,9,Neo,Anderson,06131/87 65 43,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,+49 152-765 4321,N/a,J,N,Löschen
10,11,Gandalf,Greyhame...,089 34-56789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,NaN,01522/987 6543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,.Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,N/a,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,/Wayne,123-456-7890,N/a,J,J,Löschen
15,16,Clark,Kent/,844|5435|333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,4353/45 345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,...Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen
19,19,Frodo,...Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen
20,19,Frodo,...Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen

In [27]:
df.info

<bound method DataFrame.info of     KundenID   Vorname     Nachname         Telefonnummer  \
0          1      Luke    Skywalker          0176-9876543
1          2      Leia      Organa.         (030) 2345678
2          3     Frodo      Baggins          040 876 5432
3          4   Aragorn          N/a         0151|567-8901
4          5  Hermione      Granger  +49 (0)170 123 45 67
5          6     Darth        Vader     0049 160 987 6543
6          7   Indiana        Jones          0221/3456789
7          8      Lara        Croft          0711 2345-67
8          9       Neo     Anderson        06131/87 65 43
9         10   Trinity         Moss      +49 152-765 4321
10        11   Gandalf  Greyhame...          089 34-56789
11        12     Bilbo          NaN        01522/987 6543
12        13      Jack     .Sparrow                   NaN
13        14      Tony        Stark                   N/a
14        15     Bruce       /Wayne          123-456-7890
15        16     Clark        Kent/          844|5435|333
16        17     Diana       Prince           4353/45 345
17        18     Peter       Parker       +49 170 9998887
18        19     Frodo   ...Baggins        (040) 567 7890
19        19     Frodo   ...Baggins        (040) 567 7890
20        19     Frodo   ...Baggins        (040) 567 7890

                                 Adresse Zahlender Kunde Nicht kontaktieren  \
0      /Hauptstraße 12, Berlin, 10115...              Ja               Nein
1                                    N/a               J                  N
2      Mittelstraße 34, München, 80331--            Nein                 Ja
3      --Ringstraße 78, Hamburg, 20095--               N                  J
4                                    N/a             N/a                N/a
5     /Königsallee 22, Düsseldorf, 40210              Ja               Nein
6      ...Marktplatz 5, Stuttgart, 70173            Nein                 Ja
7                                    N/a               N                  J
8                                    N/a              Ja               Nein
9                                    N/a               J                  N
10      Lindenstraße 9, Frankfurt, 60313               N                  J
11   --Goethestraße 14, Leipzig, 04109--              Ja                 Ja
12       ...Bergstraße 67, Bremen, 28195            Nein               Nein
13     /Schillerstraße 3, Dresden, 01067              Ja               Nein
14                                   N/a               J                  J
15        Mozartstraße 2, Köln, 50667...               N                  J
16      Wilhelmstraße 6, Hannover, 30159             N/a                N/a
17  --Friedrichstraße 10, Potsdam, 14467              Ja               Nein
18     Humboldtstraße 8, Erfurt, 99084--               J                  J
19     Humboldtstraße 8, Erfurt, 99084--               J                  J
20     Humboldtstraße 8, Erfurt, 99084--               J                  J

   Unnötige Spalte
0          Löschen
1          Löschen
2          Löschen
3          Löschen
4          Löschen
5          Löschen
6          Löschen
7          Löschen
8          Löschen
9          Löschen
10         Löschen
11         Löschen
12         Löschen
13         Löschen
14         Löschen
15         Löschen
16         Löschen
17         Löschen
18         Löschen
19         Löschen
20         Löschen  >

In [32]:
df.duplicated().sum()

np.int64(2)

In [33]:
df.drop_duplicates(keep='first')

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,0176-9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa.,(030) 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,040 876 5432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,N/a,0151|567-8901,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 (0)170 123 45 67,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,0049 160 987 6543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,0221/3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,0711 2345-67,N/a,N,J,Löschen
8,9,Neo,Anderson,06131/87 65 43,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,+49 152-765 4321,N/a,J,N,Löschen
10,11,Gandalf,Greyhame...,089 34-56789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,NaN,01522/987 6543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,.Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,N/a,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,/Wayne,123-456-7890,N/a,J,J,Löschen
15,16,Clark,Kent/,844|5435|333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,4353/45 345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,...Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen

In [49]:
df = df.drop_duplicates(keep='first')

In [54]:
df

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,0176-9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa,(030) 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,040 876 5432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,N/a,0151|567-8901,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 (0)170 123 45 67,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,0049 160 987 6543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,0221/3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,0711 2345-67,N/a,N,J,Löschen
8,9,Neo,Anderson,06131/87 65 43,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,+49 152-765 4321,N/a,J,N,Löschen
10,11,Gandalf,Greyhame,089 34-56789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,NaN,01522/987 6543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,N/a,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,Wayne,123-456-7890,N/a,J,J,Löschen
15,16,Clark,Kent,844|5435|333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,4353/45 345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen

In [39]:
df.duplicated().sum()

np.int64(0)

In [41]:
df["Nachname"].astype(str).str.strip(". /")

0     Skywalker
1        Organa
2       Baggins
3           N/a
4       Granger
5         Vader
6         Jones
7         Croft
8      Anderson
9          Moss
10     Greyhame
11          NaN
12      Sparrow
13        Stark
14        Wayne
15         Kent
16       Prince
17       Parker
18      Baggins
Name: Nachname, dtype: str

In [ ]:
df["Nachname"].astype(str).str.strip(". /")

In [55]:
df

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,0176-9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa,(030) 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,040 876 5432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,N/a,0151|567-8901,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 (0)170 123 45 67,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,0049 160 987 6543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,0221/3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,0711 2345-67,N/a,N,J,Löschen
8,9,Neo,Anderson,06131/87 65 43,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,+49 152-765 4321,N/a,J,N,Löschen
10,11,Gandalf,Greyhame,089 34-56789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,NaN,01522/987 6543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,N/a,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,Wayne,123-456-7890,N/a,J,J,Löschen
15,16,Clark,Kent,844|5435|333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,4353/45 345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen

In [58]:
df["Nachname"].replace(["NaN", "N/a"],"unbekannt")

0     Skywalker
1        Organa
2       Baggins
3     unbekannt
4       Granger
5         Vader
6         Jones
7         Croft
8      Anderson
9          Moss
10     Greyhame
11    unbekannt
12      Sparrow
13        Stark
14        Wayne
15         Kent
16       Prince
17       Parker
18      Baggins
Name: Nachname, dtype: str

In [60]:
df["Nachname"] = df["Nachname"].replace(["NaN", "N/a"],"unbekannt")

In [61]:
df

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,0176-9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa,(030) 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,040 876 5432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,unbekannt,0151|567-8901,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 (0)170 123 45 67,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,0049 160 987 6543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,0221/3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,0711 2345-67,N/a,N,J,Löschen
8,9,Neo,Anderson,06131/87 65 43,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,+49 152-765 4321,N/a,J,N,Löschen
10,11,Gandalf,Greyhame,089 34-56789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,unbekannt,01522/987 6543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,N/a,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,Wayne,123-456-7890,N/a,J,J,Löschen
15,16,Clark,Kent,844|5435|333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,4353/45 345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,Baggins,(040) 567 7890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen

In [67]:
import re
import phonenumbers

def telefonnummer_formatieren(num):
    # normalize input
    if num is None:
        return None
    s = str(num).strip()
    if not s or s.lower() in {"nan", "n/a", "na"}:
        return None

    # remove common separators but keep leading + and leading 00 for country codes
    # first strip spaces, dots, slashes, pipes, hyphens and parentheses
    cleaned = re.sub(r'[.\s\-/|()]+', '', s)

    # handle +49(0)... or 0049(0)... -> remove the extra 0 after country code
    if cleaned.startswith('+490'):
        cleaned = '+49' + cleaned[4:]
    if cleaned.startswith('00490'):
        cleaned = '0049' + cleaned[5:]

    # convert 00... to +...
    if cleaned.startswith('00'):
        cleaned = '+' + cleaned[2:]

    try:
        # prefer explicit international string if present
        if cleaned.startswith('+'):
            parsed = phonenumbers.parse(cleaned, None)
        else:
            parsed = phonenumbers.parse(cleaned, "DE")
        if phonenumbers.is_valid_number(parsed):
            return phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        else:
            return None
    except Exception:
        return None

In [68]:
df["Telefonnummer"].apply(telefonnummer_formatieren)

0      +49 176 9876543
1       +49 30 2345678
2       +49 40 8765432
3                  NaN
4      +49 170 1234567
5      +49 160 9876543
6      +49 221 3456789
7       +49 711 234567
8      +49 6131 876543
9                  NaN
10      +49 89 3456789
11    +49 1522 9876543
12                 NaN
13                 NaN
14                 NaN
15     +49 8445 435333
16      +49 4353 45345
17     +49 170 9998887
18      +49 40 5677890
Name: Telefonnummer, dtype: str

In [69]:
df["Telefonnummer"] = df["Telefonnummer"].apply(telefonnummer_formatieren)
df

,KundenID,Vorname,Nachname,Telefonnummer,Adresse,Zahlender Kunde,Nicht kontaktieren,Unnötige Spalte
0,1,Luke,Skywalker,+49 176 9876543,"/Hauptstraße 12, Berlin, 10115...",Ja,Nein,Löschen
1,2,Leia,Organa,+49 30 2345678,N/a,J,N,Löschen
2,3,Frodo,Baggins,+49 40 8765432,"Mittelstraße 34, München, 80331--",Nein,Ja,Löschen
3,4,Aragorn,unbekannt,NaN,"--Ringstraße 78, Hamburg, 20095--",N,J,Löschen
4,5,Hermione,Granger,+49 170 1234567,N/a,N/a,N/a,Löschen
5,6,Darth,Vader,+49 160 9876543,"/Königsallee 22, Düsseldorf, 40210",Ja,Nein,Löschen
6,7,Indiana,Jones,+49 221 3456789,"...Marktplatz 5, Stuttgart, 70173",Nein,Ja,Löschen
7,8,Lara,Croft,+49 711 234567,N/a,N,J,Löschen
8,9,Neo,Anderson,+49 6131 876543,N/a,Ja,Nein,Löschen
9,10,Trinity,Moss,NaN,N/a,J,N,Löschen
10,11,Gandalf,Greyhame,+49 89 3456789,"Lindenstraße 9, Frankfurt, 60313",N,J,Löschen
11,12,Bilbo,unbekannt,+49 1522 9876543,"--Goethestraße 14, Leipzig, 04109--",Ja,Ja,Löschen
12,13,Jack,Sparrow,NaN,"...Bergstraße 67, Bremen, 28195",Nein,Nein,Löschen
13,14,Tony,Stark,NaN,"/Schillerstraße 3, Dresden, 01067",Ja,Nein,Löschen
14,15,Bruce,Wayne,NaN,N/a,J,J,Löschen
15,16,Clark,Kent,+49 8445 435333,"Mozartstraße 2, Köln, 50667...",N,J,Löschen
16,17,Diana,Prince,+49 4353 45345,"Wilhelmstraße 6, Hannover, 30159",N/a,N/a,Löschen
17,18,Peter,Parker,+49 170 9998887,"--Friedrichstraße 10, Potsdam, 14467",Ja,Nein,Löschen
18,19,Frodo,Baggins,+49 40 5677890,"Humboldtstraße 8, Erfurt, 99084--",J,J,Löschen